[general]

#### Address & Root dir
host = "127.0.0.1"
port = 3000
root = "./dist/"

#### List of index files
index-files = "index.html"

[advanced]

#### Redirects
[[advanced.rewrites]]
source = "/"
destination = "/index.html"
redirect = 301